### ISSUE TITLE
Open related test file

### ISSUE THREAD

**Issue by Soleone** [hmatsuda/rails-transporter#73]
Right now the package seems to be opinionated towards using rspec. the default in rails is still minitest with `_test.rb` files. do you think you can add support for jumping to a unit test from a model and controller test from a controller?

**Comment by hmatsuda** [comment]
Yes I'll support to jump `_test.rb` files.

**Comment by hmatsuda** [comment]
@Soleone  I published this feature into the atom package registry right now https://atom.io/packages/rails-transporter.
But I don't get familer with minitest. If I mistake about implementation, please reopen this issue.

**Comment by Soleone** [comment]
hi @hmatsuda, thanks a lot! it seems the basic functionality is there.

that being said in my particular rails project it is not working as expected. the reason is that before rails 4 i think the folder structure was different, and a lot of old rails project will still have the following folder structure:

* `test/unit` instead of `test/models`
* `test/functional` instead of `test/controllers`

here is a source with comparison between [rails 3 docs](http://guides.rubyonrails.org/v3.2.13/testing.html#rails-sets-up-for-testing-from-the-word-go) and [rails 4 docs](http://guides.rubyonrails.org/testing.html#rails-sets-up-for-testing-from-the-word-go)

it would be great if the package could be adjusted to accommodate for both use cases, i.e.:

* look in `test/models` first and if that doesn't exist try to find the file in `test/unit`
* when suggesting to create a new file make sure to try to create it in the existing folder, so if only `test/unit` exists, suggest creating it there, otherwise suggest creating it in `test/models`
